Add idefics2 to the leaderboard
AtsuMiyai/UPD pull request #1
Opened 2024-06-06 18:12 UTC by andimarafioti

Hi 👋 

I added the code to run your evaluation with Idefics2 from Hugging Face 🤗 
I'm running this evaluation in our cluster and will submit the results to the leaderboard shortly, please let me know if you see any issues with the implementation (I already saw some unexpected results :S )

2024-06-06 22:35 UTC, AtsuMiyai requested changes
Thanks for your PR! 

Could you remove the input text from the output sentences in `vlms/idefics2/idefics2_vqa_updbench.py`? In the current version, this `outputs` has the input sentences.

Other points are LGTM for me!

2024-06-06 22:35 UTC, AtsuMiyai commented on vlms/idefics2/idefics2_vqa_updbench.py
> +                outputs = processor.batch_decode(generated_text, skip_special_tokens=True)[0]
Could you remove the input text from the output sentences? In the current version, this `outputs` has the input sentences.

Current outputs: 
> User: Which one is the correct caption of this image?
> A. A chocolate cake with icing next to plates and spoons.
> B. Stuffed teddy bear sitting next to garbage can on the side of the road.
> C. A group of baseball players playing a game of baseball.
> D. Two stainless steel sinks with mirrors and a fire extinguisher.
>  
> Assistant: D. Two stainless steel sinks with mirrors and a fire extinguisher.

Ideal outputs: 

> D. Two stainless steel sinks with mirrors and a fire extinguisher.

2024-06-10 08:42 UTC, andimarafioti commented
I addressed the changes and I'm re-running the processing + eval to see if there are any changes in performance.

2024-06-10 19:16 UTC, AtsuMiyai commented
@andimarafioti 
Thanks for your modification! 
The current version is good for merging. Thanks for your contribution!

2024-06-10 19:17 UTC, AtsuMiyai approved these changes

2024-06-10 19:17 UTC, merged